### ISSUE TITLE
Scripts DRY refactoring

### ISSUE THREAD

**Issue by horky2004** [morganjweaver/04-encode-bootcamp#9]
There is some code duplication in scripts. I propose extracting repeated functionality to a common helper, similar to the [08-Tokenized-Votes solution](https://github.com/morganjweaver/08-Tokenized-Votes/blob/0dc036922d54f98f321c97baf3e00469e2a2d2e3/Project/helpers/utils.ts). Amount of code is rather small so it should not be a problem if we clump it all in a single file for now. If it ever gets bigger, we can break it into dedicated helpers.

**Comment by morganjweaver** [comment]
Completed--please see PR
